language: ruby
rvm:
- 2.3.0
- 2.4.0

before_install:
  - npm install apn
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "gem update --system"
  - "gem update bundler"

script:
  - "sudo -u postgres createuser -s soulcast"
  - sudo -u postgres psql -c "ALTER USER soulcast WITH PASSWORD 'soulcast';"
  - bin/rake db:setup
  - bin/rake spec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.6"

sudo: "required" #for 14.04
dist: "trusty"
