language: ruby

rvm:
- 2.3.3
- 2.4.0

env:
  - TRAVIS_RUBY_VERSION="2.4.0"
  - TRAVIS_NODE_VERSION="6.9.1"

before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "gem update --system"
  - "gem update bundler"

script:
  - sudo apt-get remove --purge nodejs npm -y
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install apn
  - "sudo -u postgres createuser -s soulcast"
  - sudo -u postgres psql -c "ALTER USER soulcast WITH PASSWORD 'soulcast';"
  - bin/rake db:setup
  - bin/rake spec
cache: bundler

services:
  - postgresql

addons:
  postgresql: "9.6"

sudo: "required" #for 14.04
dist: "trusty"
